---
- name: Download saagiectl
  ansible.builtin.get_url:
    url: '{{ download_url | default("https://archive.install.saagie.io/saagiectl/" + saagie_version + "/saagiectl-" + saagie_version + "-linux-x64.zip", true) }}'
    dest: '{{ zip_location }}'
  register: download
  when: download_url and download

- name: Setting saagiectl path
  ansible.builtin.set_fact:
    saagiectl: 'saagiectl-linux-x64/bin/saagiectl'
