- name: Create the cache directory
  ansible.builtin.file:
    path: '{{ cache_directory }}'
    state: directory
    mode: '0755'
  register: cachedir

- name: Setting saagiectl install directory
  ansible.builtin.set_fact:
    saagie_install_directory: '{{ "saagiectl-" + saagie_version }}'

- name: Create the install directory
  ansible.builtin.file:
    path: '{{ (working_directory, saagie_install_directory) | join("/") }}'
    state: directory
    mode: '0755'

- include_tasks: linux.yml
  when: 'ansible_facts["os_family"] not in ["Darwin", "Windows"]'
- include_tasks: darwin.yml
  when: 'ansible_facts["os_family"] == "Darwin"'

- name: Run saagiectl
  ansible.builtin.command:
    argv: '{{ [ saagiectl ] + item }}'
    chdir: '{{ working_directory }}'
  changed_when: true
  with_list: '{{ argv }}'