name: Ansible test

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ansible:
        - '2.9'
        - '2.10'
        - '4.10'
        - '5.3'

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: Install ansible lint
      run: pip install 'ansible==${{ matrix.ansible }}' ansible-lint

    - uses: actions/checkout@v2

    - name: Lint Ansible Playbook
      run: ansible-lint

    - name: Run Ansible Playbook
      run: find . -type d -path '*/roles/*' -maxdepth 4 -execdir ansible-playbook -i localhost '{}/tests/test.yml' \;
